name: Terraform Validate

on:
  pull_request:
    
  push:
    branches:
      - main
    

permissions:
  contents: read
  pull-requests: write

jobs:
  validate:
    name: Terraform Validate + Security Scan
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "~> 1.7"

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Init (no backend)
        run: terraform init -backend=false

      - name: Terraform Validate
        run: terraform validate

      - name: Run Checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: infra/terraform-framework
          framework: terraform
          output_format: sarif
          output_file_path: checkov-results.sarif
          soft_fail: false
          check: CKV_AWS_58,CKV_AWS_79,CKV_AWS_111,CKV_AWS_115,CKV_AWS_116,CKV_AWS_117

      - name: Upload Checkov SARIF
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: checkov-results.sarif
          category: checkov-terraform
